Docs
sdkgen/sdkgen pull request #120
Opened 2020-10-28 20:50 UTC by lbguilherme

2020-11-03 18:03 UTC, dgadelha requested changes

2020-11-03 18:03 UTC, dgadelha commented on docs/index.md
> +}
Os outros exemplos utilizam 2 espaços:

```suggestion
type User {
  id: uuid
  email: string
  name: string
}
```

2020-11-03 18:03 UTC, dgadelha commented on docs/primeiro-projeto.md
> +}
```suggestion
type Post {
  id: uuid
  title: string
  body: string
  createdAt: datetime
  author: {
    name: string
  }
}
```

2020-11-03 18:32 UTC, dgadelha commented on docs/descrevendo-api.md
> +Um tipo pode conter múltiplos spreads. Caso um campo exista tanto no tipo atual quanto vindo do spread, o campo vindo do spread será utilizado. Caso um mesmo campo apareça em mais de um spread, o últ
```suggestion
Um tipo pode conter múltiplos spreads. Caso um campo exista tanto no tipo atual quanto vindo do spread, o campo vindo do spread será utilizado. Caso um mesmo campo apareça em mais de um spread, a última ocorrência prevalecerá. Note que isso significa que um spread sempre substitui o campo do tipo, em caso de conflito. Exemplo:
```

2020-11-12 01:39 UTC, dgadelha requested changes

2020-11-12 01:39 UTC, dgadelha commented on docs/aprofundando/annotations.md
> +  @description Email já validado do usuário.
```suggestion
  @description E-mail já validado do usuário.
```

2020-11-12 01:39 UTC, dgadelha commented on docs/aprofundando/datas.md
> +Como descrito na [sessão sobre tipos primitivos](../descrevendo-api.md), `date` e `datetime` possuem significados parecidos, mas fundamentalmente diferentes. Utilize `datetime` quando quer se referir
```suggestion
Como descrito na [sessão sobre tipos primitivos](../descrevendo-api.md), `date` e `datetime` possuem significados parecidos, mas fundamentalmente diferentes. Utilize `datetime` quando quiser se referir a um ponto no tempo ou `date` quando quiser se referir a uma data no calendário.
```

2020-11-12 01:39 UTC, dgadelha commented on docs/aprofundando/rest.md
> +Logo após o método o segundo elemento obrigatório do `@rest` é o caminho (ou "endpoint"). Este caminho deve começar com uma "/" e utilizar caracteres permitidos em uma URL. Neste caminho podem ser in
```suggestion
Logo após o método o segundo elemento obrigatório do `@rest` é o caminho (ou "endpoint"). Este caminho deve começar com uma "/" e utilizar caracteres permitidos em uma URL. Neste caminho podem ser incluídos alguns segmentos dinâmicos vinculados aos argumentos da função, como `/product/{id}` onde `id` é um argumento. O caminho pode incluir múltiplos destes argumentos.
```

2020-11-12 01:39 UTC, dgadelha commented on docs/aprofundando/rest.md
> +## Body
Sobre os títulos Headers e Body, vale trocar para Cabeçalhos e Corpo, já que os outros também estão em português?

2020-11-12 01:39 UTC, dgadelha commented on docs/aprofundando/rest.md
> +| Sucesso, com qualquer outro tipo de retorno                   | 200 Ok                    |
```suggestion
| Sucesso, com qualquer outro tipo de retorno                   | 200 OK                    |
```

2020-11-12 01:39 UTC, dgadelha commented on docs/descrevendo-api.md
> +Conforme uma API se torna maior e mais complexa passa a ser interessante dividir em múltiplos arquivos. Para isso a palavra chave `import` pode ser utilizada. Por exemplo:
```suggestion
Conforme uma API se torna maior e mais complexa passa a ser interessante dividir em múltiplos arquivos. Para isso a palavra-chave `import` pode ser utilizada. Por exemplo:
```

2020-11-12 01:39 UTC, dgadelha commented on docs/descrevendo-api.md
> +A descrição das funções é provavelmente a parte mais importante da sua API. Toda função possui um nome, uma lista de argumentos e opcionalmente um tipo de retorno. Todas as funções descritas estarão
```suggestion
A descrição das funções é provavelmente a parte mais importante da sua API. Toda função possui um nome, uma lista de argumentos e, opcionalmente, um tipo de retorno. Todas as funções descritas estarão expostas para serem chamadas por seus usuários, cabendo à implementação de sua API o trabalho de autenticar e autorizar acessos. Cada função deve possuir um nome claro que indique seu funcionamento, geralmente iniciando com um verbo.
```

2020-11-12 01:39 UTC, dgadelha commented on docs/descrevendo-api.md
> +Neste exemplo `Test1` terá um campo `foo` de tipo `int`, já que `...A` aparece por último. `Test2`, por sua vez, terá um campo `bar` de tipo `int`, já que spreads sempre tem prioridade a campos locai
revisar: spreads está no plural

```suggestion
Neste exemplo `Test1` terá um campo `foo` de tipo `int`, já que `...A` aparece por último. `Test2`, por sua vez, terá um campo `bar` de tipo `int`, já que spreads sempre têm prioridade a campos locais.
```

2020-11-12 01:39 UTC, dgadelha commented on docs/primeiro-projeto.md
> +A partir deste arquivo de descrição devemos gerar um arquivo de código TypeScript parece ser a base da nossa aplicação chamado `api.ts`. Esse arquivo deve ser gerado novamente sempre que o `api.sdkge
acho que isso faz mais sentido:
```suggestion
A partir deste arquivo de descrição devemos gerar um arquivo de código TypeScript para ser a base da nossa aplicação chamado `api.ts`. Esse arquivo deve ser gerado novamente sempre que o `api.sdkgen` for modificado:
```

2020-11-12 01:39 UTC, dgadelha commented on docs/targets/servidor-nodejs.md
> +Para criar um servidor em Node.js você deve criar um projeto em TypeScript e instalar o pacote NPM `@sdkgen/node-runtime`. Instale também o `@sdkgen/cli` para ter acesso aos comandos de terminal para
```suggestion
Para criar um servidor em Node.js você deve criar um projeto em TypeScript e instalar o pacote npm `[@sdkgen/node-runtime](https://www.npmjs.com/package/@sdkgen/node-runtime)`. Instale também o `[@sdkgen/cli](https://www.npmjs.com/package/@sdkgen/cli)` para ter acesso aos comandos de terminal para gerar código. Descreva a sua API em arquivos `.sdkgen`. A sugestão é criar um arquivo `api.sdkgen` contendo as definições ou importando os demais arquivos que contém essas definições de tipos e funções.
```

2020-11-12 01:39 UTC, dgadelha commented on docs/targets/servidor-nodejs.md
> +Adicione este script no seu package.json:
```suggestion
Adicione este script ao seu package.json:
```

2020-11-12 10:22 UTC, lbguilherme commented on docs/aprofundando/rest.md
> +## Body
Tenho receio de a tradução não ser entendida. Em se falando de REST, "Header" e "Body" são palavras por si só

2020-11-12 12:51 UTC, dgadelha approved these changes

2020-11-12 12:52 UTC, merged