Feat/ios
sdkgen/sdkgen pull request #377
Opened 2021-06-21 19:34 UTC by ahardmann

feat: iOS

2021-06-23 13:48 UTC, lbguilherme requested changes

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/.travis.yml
> +- pod lib lint
Remover configuração do Travis. Precisa converter em uma GitHub Action aquivalente.

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/Example/Tests/Tests.swift
> +}
Remover essa pasta "Example"

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime.podspec
> +  spec.version                 = '0.1.0'
Esse número de versão vai precisar ser sobrescrito pelo script de deploy. Sugiro então deixar 0.0.0 aqui.

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime.podspec
> +  spec.summary                 = 'Cubos sdkgen.'
"sdkgen is a tool to help design, implement and maintain good APIs with minimal effort"

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime.podspec
> +  spec.documentation_url       = 'https://github.com/sdkgen/sdkgen'
https://sdkgen.github.io

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime.podspec
> +  # spec.source_files = 'ios-runtime/SdkgenRuntime/Classes/**/*.swift'
Me parece que o correto é a linha comentada.

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime/Classes/Device.swift
> +        device["type"] = "iOS"
type é sempre minísuclo. `ios`

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime/Classes/Device.swift
> +        if let deviceId = UIDevice.current.identifierForVendor?.uuidString {
Me parece que devemos sempre usar o device-id gerado e salvo aqui, não utilizando o identifierForVendor. Até pq ele usa um formato diferente.

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime/Classes/Device.swift
> +
Tem alguma lib que provenha essa lista sem que a gente precise manter aqui? Facilmente vai ficar desatualizada. Caso contrário, tem link da fonte oficial de onde isso pode ser atualizado? Poderia deixar como comentário.

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime/Classes/SdkgenHttpClient.swift
> +            urlRequest.httpBody = try JSONSerialization.data(withJSONObject: body, options: .prettyPrinted)
Não utilizar prettyPrinted

2021-06-23 13:48 UTC, lbguilherme commented on ios-runtime/SdkgenRuntime/Classes/SdkgenHttpClient.swift
> +        urlRequest.timeoutInterval = timeoutSeconds ?? 35;
Adicionar `content-type = application/sdkgen`

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/.prettierrc
> +}
Não incluir este arquivo, já é tratado pelo @cubos/eslint-config

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +      return "Int";
Faz sentido o tipo Money ser um Decimal ou um Int64? Int tem o problema de ser só 32 bits

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +      return "String";
Faria sentido URL ser do tipo URL? https://developer.apple.com/documentation/foundation/url

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +      return "Data";
O tipo Data me parece errado aqui. Talvez o correto seja AnyObject?

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +    "Dictionary",
Tipos (String, Array, etc) não precisam entrar aqui, só keywords.

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +      return `${mangle(fieldName)}`;
não precisa usar a função mangle aqui dentro. O valor já tem que vindo com mangle de quem chamou essa função

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +      return `String(bytes: ${mangle(fieldName)}, encoding: .utf8)`;
Codificar como base64

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/src/swift-client.ts
> +  let code =`import Foundation\nimport SdkgenRuntime\n`;
Executar eslint

2021-06-23 13:48 UTC, lbguilherme commented on swift-generator/src/swift-client.ts
> +        }\n\n`;
Essas 3 funções acima poderiam ser movidas para o SwiftRuntime

2021-06-28 19:25 UTC, ahardmann commented on ios-runtime/SdkgenRuntime.podspec
> +  spec.version                 = '0.1.0'
deixei 0.0.0, tem que adicionar la no script pra essa alteração

2021-06-28 19:26 UTC, ahardmann commented on swift-generator/.prettierrc
> +}
segui o padrão dos outros porjetos `-generator`, vou remover o arquivo

2021-06-28 19:33 UTC, ahardmann commented on swift-generator/src/helpers.ts
> +      return "Data";
o Data é usado pra trabalhar com json também, mas pensando nesse caso, acho que o AnyObject se encaixa melhor mesmo

2021-06-28 19:35 UTC, ahardmann commented on swift-generator/src/helpers.ts
> +      return "String";
pensando aqui, acho que é melhor deixar como string mesmo, é mais fácil de trabalhar se eu precisar manipular ela, e gero o tipo URL pela string

2021-06-28 19:36 UTC, ahardmann commented on ios-runtime/SdkgenRuntime.podspec
> +  # spec.source_files = 'ios-runtime/SdkgenRuntime/Classes/**/*.swift'
é isso mesmo, tava usando a de cima pra testar local

2021-06-28 19:58 UTC, ahardmann commented on ios-runtime/SdkgenRuntime/Classes/Device.swift
> +
adicionei essa https://github.com/devicekit/DeviceKit

2021-06-29 12:38 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +      return "String";
Ok

2021-06-29 12:42 UTC, lbguilherme commented on swift-generator/.prettierrc
> +}
Eu estava errado, esse arquivo precisa ser mantido

2021-06-29 20:16 UTC, ahardmann commented on swift-generator/src/swift-client.ts
> +        }\n\n`;
Essa função de request, ela chama o SwiftRuntime, eu criei ela pra não ter que repetir esse código do `try catch` em todos os metodos. O handleResponse, vai pegar a reposta do servidor e devolver o objeto da API, a outra eu removi

2021-07-06 10:49 UTC, lbguilherme requested changes

2021-07-06 10:49 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +      return `${fieldName}.map({ return ${generateJsonRepresentation((type as ArrayType).base, "$0")} })`;
Soa errado. O JSON não necessariamente é um array. E `(type as ArrayType).base` vai resultar em undefined no caso dele.

2021-07-06 10:49 UTC, lbguilherme commented on swift-generator/src/swift-client.ts
> +      impl += `            request("${op.prettyName}", jsonArgs, timeoutSeconds, callback: callback)`;
Este 'callback' contem os dados em formato JSON, ele precisa ser convertido para o tipo gerado pelo `generateSwiftTypeName`. Reparei que você tem apenas o código que transforma em JSON, não o caminho oposto.

2021-07-06 10:49 UTC, lbguilherme commented on swift-generator/src/swift-client.ts
> +                    if let result = try dataString?.fromJson(returningType: T.self) {
Esse fromJson não é suficiente, pois alguns tipos tem regras especiais para serem convertidos de JSON, como o tipo `bytes` por exemplo.

2021-07-06 10:49 UTC, lbguilherme commented on swift-generator/src/swift-client.ts
> +        }\n\n`;
Mas essa função poderia ser uma protected em `SdkgenHttpClient`. Assim ela não precisa estar aqui no arquivo gerado, deixando ele menor.

2021-07-06 17:43 UTC, ahardmann commented on swift-generator/src/swift-client.ts
> +      impl += `            request("${op.prettyName}", jsonArgs, timeoutSeconds, callback: callback)`;
tem a função `fromJson<T: Decodable>(returningType: T.Type)` no runtime que faz o caminho oposto. No generator eu deixo todos os tipos de acordo com o protocolo `Codable`, ai essa função me o tipo correto

2021-07-06 17:54 UTC, ahardmann commented on swift-generator/src/swift-client.ts
> +                    if let result = try dataString?.fromJson(returningType: T.self) {
o `bytes` vai ser convertido pro tipo `Data` no `generateSwiftTypeName`. Esse tipo `T` é definido no momento do request através do `generateSwiftTypeName`

2021-07-06 18:58 UTC, lbguilherme commented on swift-generator/src/helpers.ts
> +      return `String(data: ${fieldName}, encoding: .utf8)`;
String não tem um construtor que recebe AnyObject

2021-07-06 19:28 UTC, ahardmann commented on swift-generator/src/helpers.ts
> +      return `String(data: ${fieldName}, encoding: .utf8)`;
de fato, me esqueci que havia trocado o Data pelo AnyObject, vou ajustar

2021-07-20 16:59 UTC, merged