feat: implement useSdkgenContext()
sdkgen/sdkgen pull request #382
Opened 2021-06-23 14:30 UTC by lbguilherme

Fixes #198.

This is a major change.

2021-06-24 16:56 UTC, dgadelha requested changes

2021-06-24 16:56 UTC, dgadelha commented on node-runtime/src/http-client.ts
> +    }
Eu estou achando que aqui talvez o mais apropriado seja fazer um deep merge dos contextos, já que agora o ctxArg é PartialDeep. O que acha?

2021-06-24 16:56 UTC, dgadelha commented on node-runtime/src/context-storage.ts
> +import { AsyncLocalStorage } from "async_hooks";
Precisa atualizar o README e a documentação sobre a versão do node

2021-06-28 13:57 UTC, lbguilherme commented on node-runtime/src/context-storage.ts
> +import { AsyncLocalStorage } from "async_hooks";
Feito.

2021-06-28 13:57 UTC, lbguilherme commented on node-runtime/src/http-client.ts
> +    }
Feito.

2021-06-28 19:35 UTC, dgadelha approved these changes

2021-06-29 09:55 UTC, merged