Feat/create download client page
sdkgen/sdkgen pull request #560
Opened 2021-09-23 20:33 UTC by Yansb

Now you can directly download your client file from the playground

![image](https://user-images.githubusercontent.com/24869058/134579580-d70a16c1-4e25-4a5f-a265-a42902e7287b.png)

2021-09-24 12:41 UTC, lbguilherme commented
Cloud you merge the latest commits from master? It should fix the CI.

2021-09-24 17:52 UTC, Yansb commented
sure

2021-09-30 00:53 UTC, lbguilherme submitted a review, later dismissed

2021-09-30 12:35 UTC, dgadelha requested changes

2021-09-30 12:35 UTC, dgadelha commented on playground/src/pages/downloads/index.tsx
> +        Flutter
`WEB` e `Node api` parecem tão estranhos, minha sugestão é padronizar `{Target} {Tipo}` (Flutter Client, Web Client, Node.js API, C# Client, etc)

```suggestion
      <a href="/targets/web/client.ts" className={s.downloadButton} download="client.ts">
        <FontAwesomeIcon size="xs" icon={faCode} />
        Web Client
      </a>
      <a className={s.downloadButton} href="/targets/node/client.ts" download="client.ts">
        <FontAwesomeIcon size="xs" icon={faCubes} />
        Node.js Client
      </a>
      <a className={s.downloadButton} href="/targets/node/api.ts" download="api.ts">
        <FontAwesomeIcon size="xs" icon={faServer} />
        Node.js API
      </a>
      <a className={s.downloadButton} href="/targets/flutter/client.dart" download="client.dart">
        <FontAwesomeIcon size="xs" icon={faMobile} />
        Flutter Client
```

2021-09-30 13:37 UTC, joshuapassos approved these changes

2021-09-30 14:50 UTC, lbguilherme approved these changes

2021-09-30 15:14 UTC, dgadelha approved these changes

2021-09-30 15:15 UTC, merged